# -*- coding: utf-8 -*-
"""[NRC_8393]_DennisAyo_ProyectoUnidad1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S09kFU3xIega5K1hB9KGH10JB82uZHAC
"""

!pip install faker

import pandas as pd
import uuid
import random
from faker import Faker

num_users=5000

"""BASE LEGAL"""

features =[
    "IDBaseLeg",
    "NomCap",
    "NumArt",
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

#Instantiating faker
tipo = ["Capitulo1","Capitulo2"]
df['NomCap'] = random.choices(
      tipo,
      weights=(95,15),
      k=num_users
)

df['IDBaseLeg'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDBaseLeg'].nunique()==num_users)

#Instantiating faker
tipo = ["Articulo1","Articulo2"]
df['NumArt'] = random.choices(
      tipo,
      weights=(95,15),
      k=num_users
)

df.to_csv('dataset_BaseLegal.csv')

pd.read_csv('dataset_BaseLegal.csv',index_col=0)

"""ECU911"""

features =[
    "IDEcu",
    "EstadoEcu"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDEcu'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDEcu'].nunique()==num_users)

#Instantiating faker
tipo = ["Activo","Inactivo"]
df['EstadoEcu'] = random.choices(
      tipo,
      weights=(95,15),
      k=num_users
)

df.to_csv('dataset_ECU.csv')

pd.read_csv('dataset_ECU.csv',index_col=0)

"""DEPARTAMENTO COORDINACION"""

features =[
    "IDDepCoor",
    "NombreDepCoor",
    "IDOperCallCenter"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

#Instantiating faker
tipo = ["AreaEvaluaciónLlamadas","AreaDespachoEmergencias"]
df['NombreDepCoor'] = random.choices(
      tipo,
      weights=(95,15),
      k=num_users
)

df['IDDepCoor'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDDepCoor'].nunique()==num_users)

df['IDOperCallCenter'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDOperCallCenter'].nunique()==num_users)

df.to_csv('dataset_DepCoor.csv')

pd.read_csv('dataset_DepCoor.csv',index_col=0)

"""OPERADOR CALL CENTER"""

features =[
    "IDOperCallCenter",
    "PrimerNomOpCallCenter",
    "PrimerApellOpCallCenter",
    "TelfOperCallCenter"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDOperCallCenter'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDOperCallCenter'].nunique()==num_users)

faker = Faker()

def PrimerNomOpCallCenter():
    return faker.first_name()

df['PrimerNomOpCallCenter'] = [PrimerNomOpCallCenter() for i in range(num_users)]

faker = Faker()

def PrimerApellOpCallCenter():
    return faker.last_name()

df['PrimerApellOpCallCenter'] = [PrimerApellOpCallCenter() for i in range(num_users)]

faker = Faker()

def TelfOperCallCenter():
    return faker.phone_number()

df['TelfOperCallCenter'] = [TelfOperCallCenter() for i in range(num_users)]

df.to_csv('dataset_OperadorCallCenter.csv')

pd.read_csv('dataset_OperadorCallCenter.csv',index_col=0)

"""RECIBE"""

features =[
    "IDOperCallCenter",
    "IDUsu",
    "IDDisp"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDOperCallCenter'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDOperCallCenter'].nunique()==num_users)

df['IDUsu'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDUsu'].nunique()==num_users)

df['IDDisp'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDDisp'].nunique()==num_users)

df.to_csv('dataset_recibe.csv')

pd.read_csv('dataset_recibe.csv',index_col=0)

"""USUARIOS"""

features =[
    "IDUsu",
    "PrimerNomUsu",
    "PrimerApellUsu",
    "DireccionUsu",
    "GeneroUsu"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDUsu'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDUsu'].nunique()==num_users)

faker = Faker()

def PrimerNomUsu():
    return faker.first_name()

df['PrimerNomUsu'] = [PrimerNomUsu() for i in range(num_users)]

faker = Faker()

def PrimerApellUsu():
    return faker.last_name()

df['PrimerApellUsu'] = [PrimerApellUsu() for i in range(num_users)]

faker = Faker()

def DireccionUsu():
    return faker.address()

df['DireccionUsu'] = [DireccionUsu() for i in range(num_users)]

#Instantiating faker
tipo = ["Femenino","Maculino"]
df['GeneroUsu'] = random.choices(
      tipo,
      weights=(95,15),
      k=num_users
)

df.to_csv('dataset_Usuarios.csv')

pd.read_csv('dataset_Usuarios.csv',index_col=0)

"""DISPOSITIVOS"""

features =[
    "IDDisp",
    "TipoDisp",
    "NumTelDisp"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDDisp'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDDisp'].nunique()==num_users)

#Instantiating faker
tipo = ["Movil","Convencional"]
df['TipoDisp'] = random.choices(
      tipo,
      weights=(95,15),
      k=num_users
)

faker = Faker()

def NumTelDisp():
    return faker.phone_number()

df['NumTelDisp'] = [NumTelDisp() for i in range(num_users)]

df.to_csv('dataset_Dispositivos.csv')

pd.read_csv('dataset_Dispositivos.csv',index_col=0)

"""PROVINCIA"""

features =[
    "IDProv",
    "NombreProv",
    "EstadoProv"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDProv'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDProv'].nunique()==num_users)

#Instantiating faker
tipo = ["Pichincha","Azuay","Bolivar","Cañar","Carchi","Cotopaxi","Chimborazo","Esmeraldas","Guayas","Loja","Manabi","Galapagos"]
df['NombreProv'] = random.choices(
      tipo,
      weights=(10,10,10,10,10,10,10,10,10,10,10,10),
      k=num_users
)

#Instantiating faker
tipo = ["Activo","Inactivo"]
df['EstadoProv'] = random.choices(
      tipo,
      weights=(50,50),
      k=num_users
)

df.to_csv('dataset_Provincia.csv')

pd.read_csv('dataset_Provincia.csv',index_col=0)

"""CANTON"""

features =[
    "IDCanton",
    "NombreCant",
    "EstadoCant",
    "IDProv"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDCanton'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDCanton'].nunique()==num_users)

#Instantiating faker
tipo = ["Quito","Cuenca","Guaranda","Azogues","Tulcan","Latacunga","Riobamba","Esmeraldas","Guayaquil","Loja","Chone","Rumuñahui"]
df['NombreCant'] = random.choices(
      tipo,
      weights=(95,15,20,20,20,20,20,20,20,20,20,50),
      k=num_users
)

#Instantiating faker
tipo = ["Activo","Inactivo"]
df['EstadoCant'] = random.choices(
      tipo,
      weights=(50,25),
      k=num_users
)

df['IDProv'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDProv'].nunique()==num_users)

df.to_csv('dataset_Canton.csv')

pd.read_csv('dataset_Canton.csv',index_col=0)

"""PARROQUIA"""

features =[
    "IDParroq",
    "NombreParroq",
    "EstadoParroq",
    "IDCanton",
    "IDProv"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDParroq'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDParroq'].nunique()==num_users)

#Instantiating faker
tipo = ["DMQ","Conocoto","El Carmen","Salinas","Guano","Latacunga","Cotacachi","Muisne","San Borondon","EL Cisne","Puerto Ayora","Sangolqui"]
df['NombreParroq'] = random.choices(
      tipo,
      weights=(95,55,20,20,20,20,20,20,20,20,20,50),
      k=num_users
)

#Instantiating faker
tipo = ["Activo","Inactivo"]
df['EstadoParroq'] = random.choices(
      tipo,
      weights=(50,25),
      k=num_users
)

df['IDCanton'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDCanton'].nunique()==num_users)

df['IDProv'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDProv'].nunique()==num_users)

df.to_csv('dataset_Parroquia.csv')

pd.read_csv('dataset_Parroquia.csv',index_col=0)