# -*- coding: utf-8 -*-
"""[NRC_8393]_DennisAyo_ProyectoUnidad1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S09kFU3xIega5K1hB9KGH10JB82uZHAC
"""

!pip install faker

import pandas as pd
import uuid
import random
from faker import Faker
import datetime

num_users=5000

features =[
    "IDEcu",

]# Creating a DF for these features
df = pd.DataFrame(columns=features)

"""IDEcu"""

df['IDEcu'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDEcu'].nunique()==num_users)

df.to_csv('dataset_ECU.csv')

pd.read_csv('dataset_ECU.csv',index_col=0)

"""ENTIDAD DEPARTAMENTO COORDINACION"""

features =[
    "IDDepCoor",
    "NombreDepCoor"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

#Instantiating faker
tipo = ["AreaEvaluaciónLlamadas","AreaDespachoEmergencias"]
df['NombreDepCoor'] = random.choices(
      tipo,
      weights=(95,15),
      k=num_users
)

df['IDDepCoor'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDDepCoor'].nunique()==num_users)

df.to_csv('dataset_DepCoor.csv')

pd.read_csv('dataset_DepCoor.csv',index_col=0)

"""ENTIDAD CALL CENTER"""

features =[
    "IDOperCallCenter",
    "PrimerNomOpCallCenter",
    "PrimerApellOpCallCenter",
    "TelfOperCallCenter"
]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['IDOperCallCenter'] =  [uuid.uuid4().hex for i in range(num_users)]
print(df['IDOperCallCenter'].nunique()==num_users)

faker = Faker()

def PrimerNomOpCallCenter():
    return faker.first_name()

df['PrimerNomOpCallCenter'] = [PrimerNomOpCallCenter() for i in range(num_users)]

faker = Faker()

def PrimerApellOpCallCenter():
    return faker.last_name()

df['PrimerApellOpCallCenter'] = [PrimerApellOpCallCenter() for i in range(num_users)]

faker = Faker()

def TelfOperCallCenter():
    return faker.phone_number()

df['TelfOperCallCenter'] = [TelfOperCallCenter() for i in range(num_users)]

df.to_csv('dataset_OperadorCallCenter.csv')

pd.read_csv('dataset_OperadorCallCenter.csv',index_col=0)